# Generated by Django 3.2.6 on 2021-09-05 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_choice_answer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='answer',
        ),
        migrations.AddField(
            model_name='question',
            name='answer',
            field=models.CharField(default='No answer suggested', max_length=200),
        ),
    ]
